version: '3'
services:
  frontend:
    build:
      context: ./frontend  # 프론트엔드 프로젝트 디렉토리 경로
      dockerfile: Dockerfile  # 프론트엔드 Dockerfile 이름
    ports:
      - "80:80"  # 호스트의 80 포트와 컨테이너의 80 포트 매핑
    networks:
      - network

  db:
    build:
      context: ./docker-test-db
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - ./docker-test-db/store:/var/lib/mysql
    networks:
      - network

networks:
  network:
