FROM openjdk:17-jdk-slim

# 애플리케이션을 실행할 디렉토리를 설정합니다.
WORKDIR /app

# Maven을 사용하여 Spring Boot 애플리케이션을 빌드합니다.
COPY . /app
#RUN ./mvn package  

# 빌드된 Spring Boot JAR 파일을 복사합니다.
COPY target/*.jar app.jar

# JAR 파일 실행 명령어를 지정합니다.
CMD ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]