FROM maven:3.9.4 as MAVEN_BUILD

WORKDIR /build

COPY pom.xml .

COPY src ./src

RUN mvn package -Dmaven.test.skip=true

FROM openjdk:17-jdk-slim

WORKDIR /app

ARG JAR_FILE=*.jar

COPY --from=MAVEN_BUILD /build/target/${JAR_FILE} ./app.jar

# JAR 파일 실행 명령어를 지정합니다.
CMD ["java", "-jar", "-Dspring.profiles.active=prod", "app.jar"]